### ISSUE TITLE
Multi-mode inversion yields models that do not predict the data

### ISSUE THREAD

**Issue by ariellellouch** [keurfonluu/evodcinv#12]
I seem to be getting a non-physical result when I run a 6-mode inversion of Rayleigh waves. When I lower the number of modes, the code behaves as predicted. You can see the notebook reproducing the error here:
https://www.dropbox.com/sh/9gi37zgoqg7evx0/AADD4UzR8sbPqntI9COWWaDNa?dl=0

I also join some screenshots. Sorry if this is a mistake on my side.
Picking file attached is non-standard (although a text file), there is a reader function in the jupyter notebook in the link.

Thanks!
Ariel 
[6_modes.txt](https://github.com/keurfonluu/evodcinv/files/11975428/6_modes.txt)
![6_modes](https://github.com/keurfonluu/evodcinv/assets/42511498/cb22a447-036d-49b6-b6ea-03b5c498a49f)
![2_modes](https://github.com/keurfonluu/evodcinv/assets/42511498/cd6bbf9e-ef19-4f14-b8e4-bf81fd41857c)

**Comment by keurfonluu** [comment]
Hi @ariellellouch,

Totally my fault.
``disba``  and ``evodcinv`` are using different default values for the parameter ``dc`` (the increment for the root finding algorithm), 0.005 and 0.001 respectively.
The default value in ``disba`` is too high for multimodal dispersion curves, resulting in what's called modal "jumps" (i.e., wrong association of root and mode).

Setting the same value for both ``disba``  and ``evodcinv`` will give you an output consistent with what has been calculated in ``evodcinv``:

```python
model.configure(
    optimizer="cpso",  # Evolutionary algorithm
    misfit="rmse",  # Misfit function type
    optimizer_args={
        "popsize": 200,  # Population size
        "maxiter": 200,  # Number of iterations
        "workers": 6,  # Number of cores
        "seed": 0,
    },
    dc=0.001,
)
```

and

```python
pd = PhaseDispersion(*final_model.T, dc=0.001)
```

![output](https://github.com/keurfonluu/evodcinv/assets/16566206/f9986e87-a254-4d70-9427-de76032d4f43)

**Comment by ariellellouch** [comment]
Super, thanks a lot!
Not sure if you want to change the defaults or put a note of it in the manual (these picks are from field data we just acquired, not some theoretical case), but that's a great explanation :)

**Comment by keurfonluu** [comment]
Yes, I should. I am just not sure which one to use. 0.005 is usually enough for the fundamental mode and is the default value in CPS. But 0.001 is more accurate (but slower). Anyway, if you have other questions and requests regarding ``evodcinv``, feel free to ask!

**Comment by ariellellouch** [comment]
One idea would be a simple heuristic based on the mode number, maybe? From my experience, your defaults are OK for fundamental, mode 1, and mode 2. So, for example, even something like dc = max(0.001, 0.005-0.001*mode number) could be a starting point...
